version: '3.4'

services:
  app:
    environment:
      DJANGO_SETTINGS_MODULE: {{ cookiecutter.project_app }}.settings.deploy
      DATABASE_URL: postgres://postgres@db:5432/{{ cookiecutter.project_app }}
      CACHE_HOST: cache:11211
      ENVIRONMENT: local
      DJANGO_SECRET_KEY: insecure-dev-key
      DOMAIN: localhost
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      SESSION_COOKIE_SECURE: "False"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: deploy
    command: ["uwsgi", "--show-config"]
    links:
      - db:db
    ports:
      - "8000:8000"
  cache:
    image: memcached:1.6-alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
