# Generated by Django 3.2.11 on 2022-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('GH', 'GitHub'), ('BC', 'Basecamp'), ('ZL', 'Zeplin'), ('SL', 'Slack'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
    ]
