# Generated by Django 3.2.11 on 2022-01-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinternallink',
            options={'verbose_name_plural': 'Client Internal Links'},
        ),
    ]
